name: locked_in

description: Offline-first fitness, study, habits and life transformation app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
