import 'package:flutter/material.dart';
import '../../core/app_state.dart';
import '../glow_tracks/glow_tracks_page.dart';

class DashboardPage extends StatelessWidget { final AppState state; const DashboardPage({super.key, required this.state});
  @override Widget build(BuildContext context) => AnimatedBuilder(animation: state, builder: (_, __) => ListView(padding: const EdgeInsets.fromLTRB(16, 8, 16, 24), children: [Text('Good work, ${state.profile['name'] ?? 'athlete'}.', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 4), Text('${state.profile['bodyType'] ?? 'HYBRID'} mode  •  ${state.profile['lockIn'] ?? 'STANDARD'} intensity'), const SizedBox(height: 20), Row(children: [_metric('${state.streak}', 'DAY STREAK', Icons.local_fire_department, Colors.orange), const SizedBox(width: 10), _metric('${state.xp}', 'XP', Icons.bolt, Colors.greenAccent), const SizedBox(width: 10), _metric('LV ${state.level}', state.levelName, Icons.shield, const Color(0xFFD4AF37))]), const SizedBox(height: 18), _card(context, 'TODAY\'S LOCK-IN', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Train • hydrate • study • reset', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800)), const SizedBox(height: 12), LinearProgressIndicator(value: [state.habits.values.where((x) => x).length / state.habits.length, 0.0].reduce((a, b) => a > b ? a : b), minHeight: 8), const SizedBox(height: 8), Text('${state.habits.values.where((x) => x).length}/${state.habits.length} daily actions complete')])) , const SizedBox(height: 12), _card(context, 'HYDRATION', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${state.waterMl} / ${state.waterGoal.round()} ml', style: const TextStyle(fontSize: 25, fontWeight: FontWeight.w900)), const SizedBox(height: 8), LinearProgressIndicator(value: (state.waterMl / state.waterGoal).clamp(0, 1), color: Colors.lightBlueAccent), const SizedBox(height: 10), Row(children: [FilledButton.tonal(onPressed: () => state.addWater(250), child: const Text('+250 ml')), const SizedBox(width: 8), Text('Goal adapts to bodyweight')])])), const SizedBox(height: 12), _card(context, 'NUTRITION', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${state.calories.round()} kcal  •  ${state.protein.round()}g protein', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800)), Text('Target: ${((state.profile['weight'] == null ? 70 : double.tryParse('${state.profile['weight']}') ?? 70) * 30).round()} kcal  •  ${state.proteinGoal.round()}g protein'), const SizedBox(height: 8), OutlinedButton(onPressed: () => _foodDialog(context), child: const Text('QUICK-LOG FOOD'))])), const SizedBox(height: 12), GlowTracksPage(state: state), const SizedBox(height: 12), _card(context, 'OFFLINE-FIRST', Row(children: [const Icon(Icons.cloud_off, color: Colors.amber), const SizedBox(width: 10), Expanded(child: Text('Local writes are instant. Sync engine is ready for the self-hosted API roadmap.'))]))]));
  Widget _metric(String value, String label, IconData icon, Color color) => Expanded(child: Card(child: Padding(padding: const EdgeInsets.all(12), child: Column(children: [Icon(icon, color: color), const SizedBox(height: 6), Text(value, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), Text(label, style: const TextStyle(fontSize: 10, color: Colors.white60))])));
  Widget _card(BuildContext c, String title, Widget child) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: Color(0xFFD4AF37), fontWeight: FontWeight.w900, letterSpacing: 1.2)), const SizedBox(height: 12), child])));
  Future<void> _foodDialog(BuildContext context) async { final n = TextEditingController(); final kcal = TextEditingController(text: '400'); final p = TextEditingController(text: '25'); await showDialog(context: context, builder: (_) => AlertDialog(title: const Text('Quick food log'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: n, decoration: const InputDecoration(labelText: 'Food')), TextField(controller: kcal, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Calories')), TextField(controller: p, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Protein (g)'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('CANCEL')), FilledButton(onPressed: () { state.addFood(n.text.isEmpty ? 'Meal' : n.text, double.tryParse(kcal.text) ?? 0, double.tryParse(p.text) ?? 0, 0, 0); Navigator.pop(context); }, child: const Text('LOG'))])); }
}
